fix

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -92,6 +92,11 @@ jobs:
                       export PATH=$NVM_DIR/versions/node/v22.18.0/bin:$PATH
                       cd /var/www/lms/frontend
                       git pull origin main
-                      # npm install --legacy-peer-deps
-                      # npm run build
-                      # echo "${{ secrets.SERVER_PASS }}" | sudo -S systemctl reload nginx
+                      npm install --legacy-peer-deps
+                      npm run build
+                        # pm2 bilan ishga tushirish / restart
+                      pm2 stop lms-frontend || true
+                      fuser -k 3030/tcp || true
+                      pm2 delete lms-frontend || echo "Old process not found"
+                      pm2 start npm --name "lms-frontend" -- run start:prod -- --port 3030
+                      echo "${{ secrets.SERVER_PASS }}" | sudo -S systemctl reload nginx
